label_map: {9: 0, 12: 1, 20: 2, 21: 3, 23: 4}
num_classes: 5

lr: 1e-3
drop_p: 0.2

in_channels: 3
out_channels1: 16
out_channels2: 32
out_channels3: 64
kernel_size1: 5
kernel_size2: 3
kernel_size3: 3
stride1: 2
stride2: 1
stride3: 1
padding1: 0
padding2: 0
padding3: 0
max_pool_kernel: 2
max_pool_stride: 2
