name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      build1: ${{ steps.filter.outputs.build1 }}
      build2: ${{ steps.filter.outputs.build2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build1:
              - 'src/artsy/data.py'
              - 'src/artsy/train.py'
              - 'src/artsy/model.py'
              - 'configs/data/**'
              - 'configs/model/**'
              - 'configs/trainer/**'
              - 'dockerfiles/train.dockerfile'
              - 'cloudbuild.yaml'
            build2:
              - 'src/artsy/evaluate.py'
              - 'src/artsy/visualize.py'
              - 'dockerfiles/evaluate.dockerfile'
              - 'configs/eval/**'
              - 'configs/visualize/**'

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.13", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --dev --locked

      - name: Run tests & coverage
        run: |
          uv run coverage run --source=src -m pytest -v
          uv run coverage report -m

  build1:
    needs: [test, changes]
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (needs.changes.outputs.build1 == 'true' || contains(github.event.head_commit.message, '[build]'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit build
      run: gcloud builds submit . --config cloudbuild.yaml --substitutions=_IMAGE_NAME=wikiart_train:latest

  build2:
    needs: [test, changes, build1]
    if: |
      always() &&
      needs.test.result == 'success' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (
        needs.build1.result == 'success' ||
        needs.changes.outputs.build2 == 'true'
      )
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit build
      run: gcloud builds submit . --config cloudbuild.yaml --substitutions=_IMAGE_NAME=wikiart_evaluate:latest
